#cloud-config
token: metal-token
os:
  ssh_authorized_keys:
  - ssh-rsa
  password: p@ssword
install:
  mode: create
  networks:
    harvester-mgmt:    # The management bond name. This is mandatory.
      interfaces:
      - name: eth0
      default_route: true
      method: dhcp
  device: /dev/sda
  iso_url: http://145.40.82.139/harvester-v1.0.0-amd64.iso
  tty: ttyS1,115200n8
